### PR TITLE
Update MinuteInputSetting.kt

### PR DESCRIPTION
**Pull request by e-t-l**
preliminary support for 10-sec intervals when time < 1min

### CODE REVIEW

**Comment by e-t-l** [comment]
Can this be merged? I can't replicate the development environment in the ReadMe since I don't have a Mac, but it seems like a very straightforward change. Have you tested it?

**Comment by e-t-l** [comment]
(I couldn't test it with the Github Workflow action because it requires a signing key, which I don't have)

**Comment by Giuliopime** [comment]
I'll give it a test tomorrow 👍🏼

**Comment by e-t-l** [comment]
> I'll give it a test tomorrow 👍🏼

Did you have a chance to try this out? 

  (I understand if you're busy. If you can point me towards instructions for how to generate the "signing key" that the Github Workflow requires to build, then I could do it myself. I've never published anything on the Microsoft Store so idk if there's a process to get one. Figured it would be quickest for everyone involved if you're just able to test it)

**Comment by Giuliopime** [comment]
Hey, aren't you able to test this locally? You should't need to run any github workflow. Also yeah too busy currently, will have more time after the 4th

**Comment by Giuliopime** [comment]
I'll close it as I've implemented it myself with some tweaks as this had a couple of bugs. Thanks for the contribution tho

**Pull request closed without merging**
